# Generated by Django 3.1.7 on 2021-02-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='account_pics'),
        ),
    ]
