teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.6
        offset: -0.03
      -
        axis: 0
        target: angular.z
        scale: 0.6
      -
        axis: 2
        target: linear.y
        scale: 0.3

    enable_button: 0  # L2 shoulder button
    enable_turbo_button: 5  # L1 shoulder button
          